### PR TITLE
Update for React v15

### PR DESCRIPTION
**Pull request by hosmelq**

### CODE REVIEW

**Comment by helior** [comment]
@hosmelq can you please resolve merge conflicts from previously the contributed pull-requests and if possible squash your commits where applicable?

**Comment by mmmeff** [comment]
Eagerly awaiting this, what's the status?

**Comment by Toflar** [comment]
Same here, really looking forward to this!

**Comment by Toflar** [comment]
Any estimate when this is going to be tagged so we can download it via npm? Or did I miss anything here? :)

**Comment by helior** [comment]
@Toflar I just published `0.3.2` just now — sorry for the delay everyone.

**Comment by Toflar** [comment]
No problem at all! Just installed it and works like a charm! Keep up the good work!

**Pull request merged**
