### PR TITLE
Support newer versions of React than 0.12.x

### PR DESCRIPTION
**Pull request by ultrafez**
Update the peerDependencies to support any version of React greater than 0.12.0

### CODE REVIEW

**Comment by ultrafez** [comment]
I'll have a look into this to see what changes are needed to get it working with 0.13.

**Comment by helior** [comment]
Thanks for looking into this @ultrafez

**Comment by helior** [comment]
Hey it turns out `jsdom` [stopped supporting node.js](https://github.com/tmpvar/jsdom#install) so I'm using `3.x` in devDependencies in afb4495afff921d752d8d05d8fea4151740c452e.

**Comment by ultrafez** [comment]
Ah, it was a simple fix! Great stuff - look forward to using this in a project I'm currently working on :)

**Comment by ultrafez** [comment]
Would you consider publishing a new version of react-highlighter with the 0.13.x support, so I can pull it down from npm instead of directly from GitHub?

**Comment by helior** [comment]
@ultrafez just published `react-highlighter@0.2.2` – should have done this a week ago, sorry!

**Pull request merged**
